# Generated by assistant to add is_cleared field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
