# Generated by assistant to add balance field to StudentProfile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_homeroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='balance',
            field=models.DecimalField(default=0.0, max_digits=10, decimal_places=2),
        ),
    ]
