# Generated by Django 4.2 on 2025-12-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_add_assigned_by_registrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='academic_year',
            field=models.CharField(blank=True, help_text='Format: YYYY-YYYY (e.g., 2025-2026)', max_length=9, null=True),
        ),
    ]
